### ISSUE TITLE
Tests not running per book instructions

### ISSUE THREAD

**Issue by kilathaar** [vfarcic/books-ms#23]
I'm trying to run commands as in devops 2.0 but the tests never executes (bit of nuisance considering what's trying to be accomplished here...)
```
$ vagrant ssh dev
$ cd /vagrant
$ sudo docker-compose -f docker-compose-dev.yml run feTestsLocal
```
Output yields:
```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo docker-compose -f docker-compose-dev.yml run feTestsLocal
WARNING: The DOMAIN variable is not set. Defaulting to a blank string.
>>> NPM is broken (again) so front-end tests are temporarily disabled.
mongod --help for help and startup options
Tue Dec 27 20:38:50.275 [initandlisten] MongoDB starting : pid=5 port=27017 dbpath=/data/db/ 64-bit host=0003cc679271
Tue Dec 27 20:38:50.276 [initandlisten] db version v2.4.10
Tue Dec 27 20:38:50.276 [initandlisten] git version: nogitversion
Tue Dec 27 20:38:50.276 [initandlisten] build info: Linux julia 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) x86_64 BOOST_LIB_VERSION=1_55
Tue Dec 27 20:38:50.277 [initandlisten] allocator: tcmalloc
Tue Dec 27 20:38:50.277 [initandlisten] options: {}
Tue Dec 27 20:38:50.279 [initandlisten] journal dir=/data/db/journal
Tue Dec 27 20:38:50.279 [initandlisten] recover : no journal files present, no recovery needed
Tue Dec 27 20:38:50.306 [FileAllocator] allocating new datafile /data/db/local.ns, filling with zeroes...
Tue Dec 27 20:38:50.306 [FileAllocator] creating directory /data/db/_tmp
Tue Dec 27 20:38:50.307 [FileAllocator] done allocating datafile /data/db/local.ns, size: 16MB,  took 0 secs
Tue Dec 27 20:38:50.313 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
Tue Dec 27 20:38:50.314 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0 secs
Tue Dec 27 20:38:50.315 [initandlisten] waiting for connections on port 27017
Tue Dec 27 20:38:50.316 [websvr] admin web console waiting for connections on port 28017
[info] Loading project definition from /source/project
[info] Set current project to books-ms (in build file:/source/)
[info] Compiling 2 Scala sources to /source/target/scala-2.10/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[info]   Compilation completed in 17.15 s
[info] Running com.technologyconversations.api.Service 
20:39:37.511 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Registering Scala Conversions.
20:39:37.525 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Deserializers for Scala Conversions registering
20:39:37.526 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Serializers for Scala Conversions registering
20:39:37.526 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up OptionSerializer
20:39:37.528 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaProductSerializer
20:39:37.530 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaCollectionSerializer
20:39:37.531 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Setting up ScalaRegexSerializers
20:39:37.535 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Hooking up scala.util.matching.Regex serializer
20:39:37.536 [routingSystem-akka.actor.default-dispatcher-2] DEBUG c.m.c.c.c.s.RegisterConversionHelpers$ - Reached base registration method on MongoConversionHelper.
Tue Dec 27 20:39:37.929 [initandlisten] connection accepted from 127.0.0.1:50684 #1 (1 connection now open)
[INFO] [12/27/2016 20:39:38.064] [routingSystem-akka.actor.default-dispatcher-5] [akka://routingSystem/user/IO-HTTP/listener-0] Bound to /0.0.0.0:8080
[INFO] [12/27/2016 20:39:38.065] [routingSystem-akka.actor.default-dispatcher-4] [akka://routingSystem/deadLetters] Message [akka.io.Tcp$Bound] from Actor[akka://routingSystem/user/IO-HTTP/listener-0#-1407534533] to Actor[akka://routingSystem/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

Running `sudo docker-compose -f docker-compose-dev.yml run testsLocal` work fine though.

(Since i am trying to learn something new and don't really know what i am doing at the moment, pasting console output was the best I could think of.)

**Comment by vfarcic** [comment]
There are different modes tests can be executed from that container. The feTestsLocal service monitors front-end source and re-runs tests and other processes every time there is any change. It is helpful for practicing test-driven development. However, since I wrote the book, there were quite a few changes to the libraries and the tests are failing every once in a while. I had to disable them. You can see that from https://github.com/vfarcic/books-ms/blob/master/run_tests.sh#L15. The `gulp watch` command is commented. That should be the only problem you should experience from the book (at least as far as I'm aware of).

If you would like to see those tests running, please remove the comment and rebuild the image.

**Comment by edwize** [comment]
kilathaar:
I found that I had to edit the Dockerfile.test to get node to compile properly:
Under Dependencies:
#RUN curl -sL https://deb.nodesource.com/setup_0.12 | bash -
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -

And then use "run --service-ports" to get the Books application exposed to my laptop:
Try "docker-compose -f docker-compose-dev.yml run --service-ports feTestsLocal"

I'm using VirtualBox and also had to map the VM's port 8080 to my laptops 9080. After that, I got the Book application's form at http://127.0.0.1:9080/components/tc-books/demo/index.html

With that said, the chapter so far doesn't talk about playing with the Books application, but you won't see any output in your terminal unless you fill in the Books form via the URL above. Since this is about automated testing I assume Viktor didn't expect people to hit the URL manually.

Lastly, unlike "testsLocal" completing, the "feTestsLocal" runs forever unless you ctrl-c from the terminal.

**Comment by vfarcic** [comment]
You're right about `--service-ports`. Seems that when I wrote the commands, I didn't test whether the page is available through Docker Compose (only through Docker directly). I'll publish the updated version soon.

You need to map VM port only if you're planning to use localhost/127.0.0.1. If you use VMs IP (e.g. 10.100.199.200), there's no need for a special mapping. I prefer latter since it frees me from making sure that the same port is not already opened on my host.
