### ISSUE TITLE
Update compose files to version 2 format

### ISSUE THREAD

**Issue by nartamonov** [vfarcic/books-ms#4]
It seems that version 1 is legacy and according to [official manual](https://docs.docker.com/compose/compose-file/#versioning) will be deprecated in future release of docker-compose. Version 2 is recommended format.

**Comment by vfarcic** [comment]
This repository is used in many articles and [The DevOps 2.0 Toolkit: Automating the Continuous Deployment Pipeline with Containerized Microservices](https://www.amazon.com/DevOps-2-0-Toolkit-Containerized-Microservices-ebook/dp/B01BJ4V66M). I'll have to go through all of them and make sure that, if needed, the examples are modified to reflect changes in the v2. As a quick workaround, I created a copy of all Docker Compose files and changed them to v2 format (for example, docker-compose-swarm.yml > docker-compose-swarm-v2.yml). The next step will be to do the changes in texts and, gradually, sunset the old compose files.

**Comment by wicope** [comment]
**1**

I think that [docker-compose-v2.yml](https://github.com/vfarcic/books-ms/blob/master/docker-compose-v2.yml) has a problem with links because with [docker-compose.yml](https://github.com/vfarcic/books-ms/blob/master/docker-compose.yml) work.

Code example docker-compose.yml 
```
  base:
    image: 10.100.198.200:5000/books-ms
    ports:
      - 8080
    environment:
      - SERVICE_NAME=books-ms

  app:
    extends:
      service: base
    **links:
      - db:db**

  db:
    image: mongo
```

Code example of [ServiceActor.scala](https://github.com/vfarcic/books-ms/blob/master/src/main/scala/com/technologyconversations/api/ServiceActor.scala)
```
  val address = envOrElse("DB_PORT_27017_TCP_ADDR", envOrElse("DB_HOST", "localhost"))
  val port = envOrElse("DB_PORT_27017_PORT", "27017")
  val client = MongoClient(MongoClientURI(s"mongodb://$address:$port/"))
```

Posible solution
https://docs.docker.com/compose/compose-file/#upgrading
https://docs.docker.com/compose/link-env-deprecated/


**2**
Another problem is the test because pass integ test with docker-compose.yml and docker-compose-v2.yml. With docker-compose-v2.yml should give fail test. Very likely the problem is only mine by changing code. I don't now, it seems that no matter whether the database is down or not, always pass the test integ.

Code example of [ServiceInteg.scala](https://github.com/vfarcic/books-ms/blob/master/src/test/scala/com/technologyconversations/api/ServiceInteg.scala)
```
  val domain = envOrElse("DOMAIN", "http://localhost:8080")
  val uri = s"$domain/api/v1/books"

  s"GET $uri" should {

    "return OK" in {
      val response: HttpResponse[String] = Http(uri).asString
      response.code must equalTo(200)
}
```

Some logs ngnix

10.100.198.1 - - [27/Sep/2016:12:37:46 +0000] "PUT /api/v1/books HTTP/1.1" 500 217 "http://10.100.198.201:8888/" "Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0" 10.100.198.201:32769 10.045 
10.100.198.1 - - [27/Sep/2016:13:18:23 +0000] "GET /api/v1/books HTTP/1.1" 499 0 "http://10.100.198.200:8080/job/books-ms-ansible/273/console" "Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0" 10.100.198.201:32769 - 
2016/09/27 13:18:25 [error] 9#9: *24 upstream prematurely closed connection while reading response header from upstream, client: 10.100.198.1, server: _, request: "GET /api/v1/books HTTP/1.1", upstream: "http://10.100.198.201:32769/api/v1/books", host: "10.100.198.201:8888", referrer: "http://10.100.198.200:8080/job/books-ms-ansible/273/console"
10.100.198.1 - - [27/Sep/2016:13:18:25 +0000] "GET /api/v1/books HTTP/1.1" 502 330 "http://10.100.198.200:8080/job/books-ms-ansible/273/console" "Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0" 10.100.198.201:32769 1.051 

Some logs mongodb (i change a lot of code, in my code books-ms is mongodb)

[ERROR] [09/27/2016 14:49:41.136] [routingSystem-akka.actor.default-dispatcher-6] [akka://routingSystem/user/service] Error during processing of request HttpRequest(GET,http://mongodb/api/v1/books,List(Upgrade-Insecure-Requests: 1, Cookie: _gorilla_csrf=MTQ3NDk2MjQzOXxJblJEZWpCUldrWktkbFl3VHpBdldXTTRWRWM0UzBKaFozZEZPRWRaUTBKMFRtOUxhalo0T0hNd2JrRTlJZ289fJjj3fV5r5AVr-CHcDbC6Ufr-y5FBTQM-Xuuqx6pJBxc; csrfToken=v6hPJ3LX+nzzoKoQs1KJgex05LD+Dyq7SOGVdEREg1QLhLtm455HIf1zXAxCYzWp+tQk//hvCtZ+YzafW2hRJA==, Referer: http://10.100.198.200:8080/job/books-ms-ansible/273/console, Accept-Encoding: gzip, deflate, Accept-Language: es-ES, es, en-US, en, User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0, Connection: close, Host: mongodb),Empty,HTTP/1.0)
com.mongodb.MongoTimeoutException: Timed out while waiting to connect after 2342 ms

[ERROR] [09/27/2016 14:50:01.487] [routingSystem-akka.actor.default-dispatcher-6] [akka://routingSystem/user/service] Error during processing of request HttpRequest(PUT,http://mongodb/api/v1/books,List(Cookie: _gorilla_csrf=MTQ3NDk2MjQzOXxJblJEZWpCUldrWktkbFl3VHpBdldXTTRWRWM0UzBKaFozZEZPRWRaUTBKMFRtOUxhalo0T0hNd2JrRTlJZ289fJjj3fV5r5AVr-CHcDbC6Ufr-y5FBTQM-Xuuqx6pJBxc; csrfToken=v6hPJ3LX+nzzoKoQs1KJgex05LD+Dyq7SOGVdEREg1QLhLtm455HIf1zXAxCYzWp+tQk//hvCtZ+YzafW2hRJA==, Referer: http://10.100.198.201:8888/, Content-Type: application/json, Accept-Encoding: gzip, deflate, Accept-Language: es-ES, es, en-US, en, User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0, Content-Length: 52, Connection: close, Host: mongodb),HttpEntity(application/json,{"_id":4,"title":"d","author":"d","description":"d"}),HTTP/1.0)
com.mongodb.MongoTimeoutException: Timed out while waiting for a server that matches AnyServerSelector{} after 8 ms

Regards
