### ISSUE TITLE
Development Environment Setup Vagrant on Windows 10 with Hyper-V

### ISSUE THREAD

**Issue by klayeus** [vfarcic/books-ms#61]
the vagrant box "ubuntu/trusty64" seems to not support hyper-v on Windows 10.

Is there an alternative to get it working?

Refering to page 56 of "The DevOps 2.0 Toolkit". The command "vagrant up dev" throughs an error, that the box is not supported.

**Comment by vfarcic** [comment]
You should be able to change it to any other Ubuntu distribution that is supported on Windows 10 with Hyper-V. You'll just need to query Vagrant images and find one that fits your situation.

As a side note, I discontinued the book quite some time ago. I don't think it is a good way to do things in 2019. A lot has changed since I wrote it. The book is probably still useful, but not as a way to know what to do today, but rather as a way to see how was the industry back then. While it was valid in the past, today I think of it as a history book rather than a technical one.

**Comment by klayeus** [comment]
Thanks! I will read it through, since I got it, and then continue through the next books of you. I really like them so far and learned a lot.
