### ISSUE TITLE
Ansible script does not work anymore

### ISSUE THREAD

**Issue by dulsi** [vfarcic/books-ms#63]
In ansible/roles/docker/tasks/main.yml, the repository has moved to:

repo: deb https://download.docker.com/linux/ubuntu trusty stable

The package is no longer docker-engine. It is docker-ce.

name: docker-ce

That's no quite enough to get everything running. I also had to add:

sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
sudo apt-get update
sudo apt-get install containerd.io
sudo apt-get install docker.io

(I don't know if the apt-repository or containerd.io are needed or not.)

After that I could start the first docker container. However docker-compose failed. I needed to set COMPOSE_API_VERSION to get that running.

sudo COMPOSE_API_VERSION=1.18 docker-compose -f docker-compose-dev.yml run feTestsLocal

Alas test cases are still not running:

>>> NPM is broken (again) so front-end tests are temporarily disabled.

**Comment by vfarcic** [comment]
That repository was created for a book (The DevOps 2.0 Toolkit) that was discontinued for quite some time now since I do not believe it represents the processes and the tools I believe are useful today. It is too old.

Did you get the book recently or is that repo used in one of the articles I wrote?

**Comment by dulsi** [comment]
The book was recommended to me recently. I thought maybe I should try one of your later devops books but the person who recommended it says the later ones assume you read 2.0. Do you have a book that is a better starting point?

**Comment by vfarcic** [comment]
If you are interested in containers, there is only one platform worth exploring (Kubernetes) and you might want to start with https://www.devopstoolkitseries.com/posts/devops-23/. Don't bother with 2.1 and 2.2 since they are focused on Docker which is, in most cases, not useful anymore.

On the other hand, if you are interested in a wider range of topics, https://www.devopstoolkitseries.com/posts/catalog/ might be a good start. However, the only assumption in that one is that you have at least a basic understanding of Kubernetes. Kubernetes is not the focus of the book, but it is used in quite a few sections.

You can get a free sample from Udemy of both of those. The latter (the catalog) is also available from Udemy where you can get preview sections.

P.S. All that does not mean that others are not a good choice but, if you are a beginner, you might want to start with one of those two.
